'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../client.html'),'utf8');
const start=html.indexOf('function endpoint('),end=html.indexOf('// --- Theme ---',start);assert(start>=0&&end>start);
function harness(token='synthetic-client',status=200){const requests=[];let logouts=0;
 const c=vm.createContext({URL,Headers,state:{token},window:{location:{origin:'https://fixture.test'}},
  logout:()=>logouts++,fetch:async(url,init)=>{requests.push({url,init});return {ok:status===200,status,headers:new Headers({'Content-Type':'application/json'}),json:async()=>({ok:true}),text:async()=>''};}});
 vm.runInContext(html.slice(start,end),c);return {c,requests,logouts:()=>logouts};}
test('client JSON API uses its own bearer header and no query token',async()=>{const h=harness();await h.c.api('/client/api/calls',{params:{days:14}});const r=h.requests[0];assert.equal(new URL(r.url).searchParams.has('token'),false);assert.equal(new URL(r.url).searchParams.get('days'),'14');assert.equal(r.init.headers.get('Authorization'),'Bearer synthetic-client');});
test('existing mutation payload/content type survives transport change',async()=>{const h=harness();await h.c.api('/client/api/calls/fixture/note',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"note":"synthetic"}'});assert.equal(h.requests[0].init.body,'{"note":"synthetic"}');assert.equal(h.requests[0].init.headers.get('Content-Type'),'application/json');assert.equal(h.requests[0].init.method,'POST');});
test('explicit auth is preserved; explicit query credential retains conflict detection',async()=>{const h=harness();await h.c.api('/client/api/calls',{headers:{Authorization:'Bearer explicit'}});assert.equal(h.requests[0].init.headers.get('Authorization'),'Bearer explicit');assert.equal(new URL(h.requests[0].url).searchParams.has('token'),false);await h.c.api('/client/api/calls',{params:{token:'explicit-query'},headers:{Authorization:'Bearer explicit'}});assert.equal(new URL(h.requests[1].url).searchParams.get('token'),'explicit-query');});
test('native media and non-header-safe legacy credentials keep query transport',async()=>{const h=harness('synthetic-é');await h.c.api('/client/api/calls');assert.equal(new URL(h.requests[0].url).searchParams.get('token'),'synthetic-é');assert.equal(h.requests[0].init.headers.has('Authorization'),false);const media=new URL(h.c.endpoint('/client/api/voice-preview'));assert.equal(media.searchParams.get('token'),'synthetic-é');});
test('401 logs out and rejects; it does not resolve as an empty data response',async()=>{const h=harness('synthetic',401);await assert.rejects(h.c.api('/client/api/calls'),/Sign-in required/);assert.equal(h.logouts(),1);});
