'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../client.html'),'utf8');
const start=html.indexOf('async function openDrawer('),end=html.indexOf('// --- Driver.js tour ---',start);assert(start>=0&&end>start);
function harness(){const requests=[],nodes={'#drawerBackdrop':{classList:{add(){},remove(){}}},'#drawerContent':{innerHTML:''},'#drawerNote':{value:'synthetic note'},'#drawerSaveNote':{}},alerts=[];
 const c=vm.createContext({state:{drawerRequest:0,drawerCallId:'',drawerLoadedId:'',noteSaving:false},qs:s=>nodes[s],esc:String,jobDetailsBlock:()=>'',prettyEvent:()=>'',cleanSummary:String,toast:()=>{},alert:t=>alerts.push(t),
 api:(url,opts)=>new Promise((resolve,reject)=>requests.push({url,opts,resolve,reject}))});vm.runInContext(html.slice(start,end),c);return {c,requests,nodes,alerts};}
const detail=id=>({call_id:id,caller_name:id,events:[],notes:[]});
test('late response cannot replace a newer selected call',async()=>{const h=harness(),a=h.c.openDrawer('old'),b=h.c.openDrawer('new');h.requests[1].resolve(detail('new'));await b;h.requests[0].resolve(detail('old'));await a;assert.equal(h.c.state.drawerLoadedId,'new');assert.match(h.nodes['#drawerContent'].innerHTML,/new/);assert.doesNotMatch(h.nodes['#drawerContent'].innerHTML,/saveNote\('old'\)/);});
test('close invalidates late success or failure',async()=>{for(const failure of [false,true]){const h=harness(),p=h.c.openDrawer('old');h.c.closeDrawer();const before=h.nodes['#drawerContent'].innerHTML;if(failure)h.requests[0].reject(Error('old failure'));else h.requests[0].resolve(detail('old'));await p;assert.equal(h.nodes['#drawerContent'].innerHTML,before);assert.equal(h.c.state.drawerLoadedId,'');}});
test('mismatched details cannot become a writable editor',async()=>{const h=harness(),p=h.c.openDrawer('selected');h.requests[0].resolve(detail('wrong'));await p;assert.equal(h.c.state.drawerLoadedId,'');await h.c.saveNote('selected');assert.equal(h.requests.length,1);});
test('save completion after navigation never clears or reopens the new call',async()=>{const h=harness();Object.assign(h.c.state,{drawerLoadedId:'old',drawerCallId:'old'});const p=h.c.saveNote('old');h.c.closeDrawer();h.nodes['#drawerNote'].value='new draft';h.requests[0].resolve({saved:true});await p;assert.equal(h.nodes['#drawerNote'].value,'new draft');assert.equal(h.requests.length,1);assert.equal(h.c.state.noteSaving,false);});
test('double save is one request and newer draft is preserved',async()=>{const h=harness();Object.assign(h.c.state,{drawerLoadedId:'call',drawerCallId:'call'});const p=h.c.saveNote('call');await h.c.saveNote('call');assert.equal(h.requests.length,1);h.nodes['#drawerNote'].value='new draft';h.requests[0].resolve({saved:true});await p;assert.equal(h.nodes['#drawerNote'].value,'new draft');assert.equal(h.requests.length,1);assert.equal(h.nodes['#drawerSaveNote'].disabled,false);});
